In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
# Dataset importing
df = pd.read_csv("D:\Imarticus\PROJECTS\SOCIAL MEDIA ANALYTICS\DATASETS\Social Media Analytics 2024 Noisy un clear dataset.csv")
# General things to do 
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account_id        8000 non-null   object
 1   post_id           8000 non-null   object
 2   id_created_date   8000 non-null   object
 3   data_source       8000 non-null   object
 4   posting_device    8000 non-null   object
 5   platform          8000 non-null   object
 6   post_date         8000 non-null   object
 7   post_time         8000 non-null   object
 8   day               8000 non-null   object
 9   hour              8000 non-null   float64
 10  time_slot         8000 non-null   object
 11  content_category  8000 non-null   object
 12  content_format    8000 non-null   object
 13  reach             8000 non-null   float64
 14  likes             8000 non-null   float64
 15  comments          8000 non-null   float64
 16  shares            8000 non-null   float64
 17  engagement        8000 non-null   float64
 18  engagement_rate   8000 non-null   float64
dtypes: float64(7), object(12)
memory usage: 1.2+ MB

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
count,8000,8000,8000,8000,8000,8000,8000,8000,8000,8000.000000,8000,8000,8000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
unique,5276,8000,420,3,3,3,366,72,7,NaN,4,6,6,NaN,NaN,NaN,NaN,NaN,NaN
top,ACC_1255,POST_207983,2024-03-16,System_B,Web,Instagram,2024-10-29,18:15,Wednesday,NaN,Evening,Business,Video,NaN,NaN,NaN,NaN,NaN,NaN
freq,6,1,36,2708,2707,3139,36,157,1198,NaN,2823,1395,2006,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.601125,NaN,NaN,NaN,79582.335125,6274.441813,933.782938,671.536875,7527.289125,0.094874
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.120869,NaN,NaN,NaN,29463.241420,2865.054897,488.600524,382.474754,3694.436179,0.029061
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,25478.000000,1162.000000,118.000000,62.000000,139.000000,0.014500
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,NaN,NaN,57608.250000,4141.750000,566.750000,372.000000,4889.750000,0.076000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.000000,NaN,NaN,NaN,75051.000000,5717.000000,838.000000,607.000000,6945.000000,0.097000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,96949.750000,7873.250000,1207.000000,888.000000,9694.250000,0.117000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.000000,NaN,NaN,NaN,155962.000000,13470.500000,2167.375000,1662.000000,16901.000000,0.153000

In [31]:
# Cleaning the column names first
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
df.columns

Index(['account_id', 'post_id', 'id_created_date', 'data_source',
       'posting_device', 'platform', 'post_date', 'post_time', 'day', 'hour',
       'time_slot', 'content_category', 'content_format', 'reach', 'likes',
       'comments', 'shares', 'engagement', 'engagement_rate'],
      dtype='object')

In [13]:
# Checking duplicates
df.duplicated().sum()
# Drop duplicates
df = df.drop_duplicates()
df

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
0,ACC_7336,POST_200000,2024-04-27,System_A,Mobile,YouTube,2024-05-09,21:15,Thursday,21.0,Evening,Entertainment,Shorts,85350.0,10087.0,1130.000,740.0,11957.0,0.140
1,ACC_6851,POST_200001,2024-01-20,System_A,Creator Studio,Instagram,2024-01-21,21:00,Sunday,21.0,Evening,Education,Carousel,116999.0,7415.0,1995.000,1493.0,10903.0,0.093
2,ACC_1381,POST_200002,2023-11-25,System_C,Creator Studio,YouTube,2024-01-12,10:15,Friday,10.0,Morning,Tech,Shorts,44142.0,4258.0,443.000,267.0,4968.0,0.113
3,ACC_2851,POST_200003,2024-02-26,System_B,Creator Studio,Instagram,2024-03-24,18:00,Sunday,18.0,Evening,Entertainment,Carousel,155962.0,13398.0,2167.375,1662.0,16901.0,0.103
4,ACC_3976,POST_200004,2024-10-18,System_A,Web,Instagram,2024-12-13,07:15,Friday,7.0,Morning,Lifestyle,Reel,104647.0,10536.0,1933.000,1183.0,13652.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,ACC_6122,POST_207995,2024-06-01,System_C,Creator Studio,Facebook,2024-07-14,11:15,Sunday,11.0,Morning,Sports,Video,63764.0,5717.0,718.000,543.0,1261.0,0.020
7996,ACC_9163,POST_207996,2024-08-11,System_B,Web,YouTube,2024-09-25,13:30,Wednesday,13.0,Afternoon,Entertainment,Shorts,96142.0,3920.0,1523.000,831.0,6274.0,0.065
7997,ACC_3786,POST_207997,2024-07-30,System_B,Mobile,Facebook,2024-08-28,14:15,Wednesday,14.0,Afternoon,Lifestyle,Text,29221.0,3196.0,508.000,367.0,4071.0,0.139
7998,ACC_2754,POST_207998,2024-08-02,System_A,Creator Studio,Instagram,2024-09-08,22:00,Sunday,22.0,Night,Business,Reel,87859.0,6740.0,622.000,607.0,7362.0,0.084
7999,ACC_6888,POST_207999,2024-03-09,System_B,Mobile,Instagram,2024-04-27,22:30,Saturday,22.0,Night,Entertainment,Image,155962.0,13470.5,2167.375,1450.0,16901.0,0.141

In [14]:
# CONVERTING THE DATA TYPES OF THE DATASET 
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns
df

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
0,ACC_7336,POST_200000,2024-04-27,System_A,Mobile,YouTube,2024-05-09,21:15,Thursday,21.0,Evening,Entertainment,Shorts,85350.0,10087.0,1130.000,740.0,11957.0,0.140
1,ACC_6851,POST_200001,2024-01-20,System_A,Creator Studio,Instagram,2024-01-21,21:00,Sunday,21.0,Evening,Education,Carousel,116999.0,7415.0,1995.000,1493.0,10903.0,0.093
2,ACC_1381,POST_200002,2023-11-25,System_C,Creator Studio,YouTube,2024-01-12,10:15,Friday,10.0,Morning,Tech,Shorts,44142.0,4258.0,443.000,267.0,4968.0,0.113
3,ACC_2851,POST_200003,2024-02-26,System_B,Creator Studio,Instagram,2024-03-24,18:00,Sunday,18.0,Evening,Entertainment,Carousel,155962.0,13398.0,2167.375,1662.0,16901.0,0.103
4,ACC_3976,POST_200004,2024-10-18,System_A,Web,Instagram,2024-12-13,07:15,Friday,7.0,Morning,Lifestyle,Reel,104647.0,10536.0,1933.000,1183.0,13652.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,ACC_6122,POST_207995,2024-06-01,System_C,Creator Studio,Facebook,2024-07-14,11:15,Sunday,11.0,Morning,Sports,Video,63764.0,5717.0,718.000,543.0,1261.0,0.020
7996,ACC_9163,POST_207996,2024-08-11,System_B,Web,YouTube,2024-09-25,13:30,Wednesday,13.0,Afternoon,Entertainment,Shorts,96142.0,3920.0,1523.000,831.0,6274.0,0.065
7997,ACC_3786,POST_207997,2024-07-30,System_B,Mobile,Facebook,2024-08-28,14:15,Wednesday,14.0,Afternoon,Lifestyle,Text,29221.0,3196.0,508.000,367.0,4071.0,0.139
7998,ACC_2754,POST_207998,2024-08-02,System_A,Creator Studio,Instagram,2024-09-08,22:00,Sunday,22.0,Night,Business,Reel,87859.0,6740.0,622.000,607.0,7362.0,0.084
7999,ACC_6888,POST_207999,2024-03-09,System_B,Mobile,Instagram,2024-04-27,22:30,Saturday,22.0,Night,Entertainment,Image,155962.0,13470.5,2167.375,1450.0,16901.0,0.141

In [15]:
#FILLING THE NA VALUES 
for col in num_cols:
    if df[col].isna().sum() > 0:
        df[col] = df[col].fillna(df[col].median())
df

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
0,ACC_7336,POST_200000,2024-04-27,System_A,Mobile,YouTube,2024-05-09,21:15,Thursday,21.0,Evening,Entertainment,Shorts,85350.0,10087.0,1130.000,740.0,11957.0,0.140
1,ACC_6851,POST_200001,2024-01-20,System_A,Creator Studio,Instagram,2024-01-21,21:00,Sunday,21.0,Evening,Education,Carousel,116999.0,7415.0,1995.000,1493.0,10903.0,0.093
2,ACC_1381,POST_200002,2023-11-25,System_C,Creator Studio,YouTube,2024-01-12,10:15,Friday,10.0,Morning,Tech,Shorts,44142.0,4258.0,443.000,267.0,4968.0,0.113
3,ACC_2851,POST_200003,2024-02-26,System_B,Creator Studio,Instagram,2024-03-24,18:00,Sunday,18.0,Evening,Entertainment,Carousel,155962.0,13398.0,2167.375,1662.0,16901.0,0.103
4,ACC_3976,POST_200004,2024-10-18,System_A,Web,Instagram,2024-12-13,07:15,Friday,7.0,Morning,Lifestyle,Reel,104647.0,10536.0,1933.000,1183.0,13652.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,ACC_6122,POST_207995,2024-06-01,System_C,Creator Studio,Facebook,2024-07-14,11:15,Sunday,11.0,Morning,Sports,Video,63764.0,5717.0,718.000,543.0,1261.0,0.020
7996,ACC_9163,POST_207996,2024-08-11,System_B,Web,YouTube,2024-09-25,13:30,Wednesday,13.0,Afternoon,Entertainment,Shorts,96142.0,3920.0,1523.000,831.0,6274.0,0.065
7997,ACC_3786,POST_207997,2024-07-30,System_B,Mobile,Facebook,2024-08-28,14:15,Wednesday,14.0,Afternoon,Lifestyle,Text,29221.0,3196.0,508.000,367.0,4071.0,0.139
7998,ACC_2754,POST_207998,2024-08-02,System_A,Creator Studio,Instagram,2024-09-08,22:00,Sunday,22.0,Night,Business,Reel,87859.0,6740.0,622.000,607.0,7362.0,0.084
7999,ACC_6888,POST_207999,2024-03-09,System_B,Mobile,Instagram,2024-04-27,22:30,Saturday,22.0,Night,Entertainment,Image,155962.0,13470.5,2167.375,1450.0,16901.0,0.141

In [16]:
# FILLING THE CATEGORICAL VALUES USING MODE
for col in cat_cols:
    if df[col].isna().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])
df

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
0,ACC_7336,POST_200000,2024-04-27,System_A,Mobile,YouTube,2024-05-09,21:15,Thursday,21.0,Evening,Entertainment,Shorts,85350.0,10087.0,1130.000,740.0,11957.0,0.140
1,ACC_6851,POST_200001,2024-01-20,System_A,Creator Studio,Instagram,2024-01-21,21:00,Sunday,21.0,Evening,Education,Carousel,116999.0,7415.0,1995.000,1493.0,10903.0,0.093
2,ACC_1381,POST_200002,2023-11-25,System_C,Creator Studio,YouTube,2024-01-12,10:15,Friday,10.0,Morning,Tech,Shorts,44142.0,4258.0,443.000,267.0,4968.0,0.113
3,ACC_2851,POST_200003,2024-02-26,System_B,Creator Studio,Instagram,2024-03-24,18:00,Sunday,18.0,Evening,Entertainment,Carousel,155962.0,13398.0,2167.375,1662.0,16901.0,0.103
4,ACC_3976,POST_200004,2024-10-18,System_A,Web,Instagram,2024-12-13,07:15,Friday,7.0,Morning,Lifestyle,Reel,104647.0,10536.0,1933.000,1183.0,13652.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,ACC_6122,POST_207995,2024-06-01,System_C,Creator Studio,Facebook,2024-07-14,11:15,Sunday,11.0,Morning,Sports,Video,63764.0,5717.0,718.000,543.0,1261.0,0.020
7996,ACC_9163,POST_207996,2024-08-11,System_B,Web,YouTube,2024-09-25,13:30,Wednesday,13.0,Afternoon,Entertainment,Shorts,96142.0,3920.0,1523.000,831.0,6274.0,0.065
7997,ACC_3786,POST_207997,2024-07-30,System_B,Mobile,Facebook,2024-08-28,14:15,Wednesday,14.0,Afternoon,Lifestyle,Text,29221.0,3196.0,508.000,367.0,4071.0,0.139
7998,ACC_2754,POST_207998,2024-08-02,System_A,Creator Studio,Instagram,2024-09-08,22:00,Sunday,22.0,Night,Business,Reel,87859.0,6740.0,622.000,607.0,7362.0,0.084
7999,ACC_6888,POST_207999,2024-03-09,System_B,Mobile,Instagram,2024-04-27,22:30,Saturday,22.0,Night,Entertainment,Image,155962.0,13470.5,2167.375,1450.0,16901.0,0.141

In [17]:
# Convert date columns
df['post_date'] = pd.to_datetime(df['post_date'], errors='coerce')
# If conversion created NaT, fill again
df['post_date'] = df['post_date'].fillna(df['post_date'].mode()[0])
df

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
0,ACC_7336,POST_200000,2024-04-27,System_A,Mobile,YouTube,2024-05-09,21:15,Thursday,21.0,Evening,Entertainment,Shorts,85350.0,10087.0,1130.000,740.0,11957.0,0.140
1,ACC_6851,POST_200001,2024-01-20,System_A,Creator Studio,Instagram,2024-01-21,21:00,Sunday,21.0,Evening,Education,Carousel,116999.0,7415.0,1995.000,1493.0,10903.0,0.093
2,ACC_1381,POST_200002,2023-11-25,System_C,Creator Studio,YouTube,2024-01-12,10:15,Friday,10.0,Morning,Tech,Shorts,44142.0,4258.0,443.000,267.0,4968.0,0.113
3,ACC_2851,POST_200003,2024-02-26,System_B,Creator Studio,Instagram,2024-03-24,18:00,Sunday,18.0,Evening,Entertainment,Carousel,155962.0,13398.0,2167.375,1662.0,16901.0,0.103
4,ACC_3976,POST_200004,2024-10-18,System_A,Web,Instagram,2024-12-13,07:15,Friday,7.0,Morning,Lifestyle,Reel,104647.0,10536.0,1933.000,1183.0,13652.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,ACC_6122,POST_207995,2024-06-01,System_C,Creator Studio,Facebook,2024-07-14,11:15,Sunday,11.0,Morning,Sports,Video,63764.0,5717.0,718.000,543.0,1261.0,0.020
7996,ACC_9163,POST_207996,2024-08-11,System_B,Web,YouTube,2024-09-25,13:30,Wednesday,13.0,Afternoon,Entertainment,Shorts,96142.0,3920.0,1523.000,831.0,6274.0,0.065
7997,ACC_3786,POST_207997,2024-07-30,System_B,Mobile,Facebook,2024-08-28,14:15,Wednesday,14.0,Afternoon,Lifestyle,Text,29221.0,3196.0,508.000,367.0,4071.0,0.139
7998,ACC_2754,POST_207998,2024-08-02,System_A,Creator Studio,Instagram,2024-09-08,22:00,Sunday,22.0,Night,Business,Reel,87859.0,6740.0,622.000,607.0,7362.0,0.084
7999,ACC_6888,POST_207999,2024-03-09,System_B,Mobile,Instagram,2024-04-27,22:30,Saturday,22.0,Night,Entertainment,Image,155962.0,13470.5,2167.375,1450.0,16901.0,0.141

In [18]:
# Checking the outliers
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])
df

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
0,ACC_7336,POST_200000,2024-04-27,System_A,Mobile,YouTube,2024-05-09,21:15,Thursday,21.0,Evening,Entertainment,Shorts,85350.0,10087.0,1130.000,740.0,11957.0,0.140
1,ACC_6851,POST_200001,2024-01-20,System_A,Creator Studio,Instagram,2024-01-21,21:00,Sunday,21.0,Evening,Education,Carousel,116999.0,7415.0,1995.000,1493.0,10903.0,0.093
2,ACC_1381,POST_200002,2023-11-25,System_C,Creator Studio,YouTube,2024-01-12,10:15,Friday,10.0,Morning,Tech,Shorts,44142.0,4258.0,443.000,267.0,4968.0,0.113
3,ACC_2851,POST_200003,2024-02-26,System_B,Creator Studio,Instagram,2024-03-24,18:00,Sunday,18.0,Evening,Entertainment,Carousel,155962.0,13398.0,2167.375,1662.0,16901.0,0.103
4,ACC_3976,POST_200004,2024-10-18,System_A,Web,Instagram,2024-12-13,07:15,Friday,7.0,Morning,Lifestyle,Reel,104647.0,10536.0,1933.000,1183.0,13652.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,ACC_6122,POST_207995,2024-06-01,System_C,Creator Studio,Facebook,2024-07-14,11:15,Sunday,11.0,Morning,Sports,Video,63764.0,5717.0,718.000,543.0,1261.0,0.020
7996,ACC_9163,POST_207996,2024-08-11,System_B,Web,YouTube,2024-09-25,13:30,Wednesday,13.0,Afternoon,Entertainment,Shorts,96142.0,3920.0,1523.000,831.0,6274.0,0.065
7997,ACC_3786,POST_207997,2024-07-30,System_B,Mobile,Facebook,2024-08-28,14:15,Wednesday,14.0,Afternoon,Lifestyle,Text,29221.0,3196.0,508.000,367.0,4071.0,0.139
7998,ACC_2754,POST_207998,2024-08-02,System_A,Creator Studio,Instagram,2024-09-08,22:00,Sunday,22.0,Night,Business,Reel,87859.0,6740.0,622.000,607.0,7362.0,0.084
7999,ACC_6888,POST_207999,2024-03-09,System_B,Mobile,Instagram,2024-04-27,22:30,Saturday,22.0,Night,Entertainment,Image,155962.0,13470.5,2167.375,1450.0,16901.0,0.141

In [19]:
# Example checks
df = df[df['likes'] >= 0]
df = df[df['shares'] >= 0]
df = df[df['comments'] >= 0]
df

,account_id,post_id,id_created_date,data_source,posting_device,platform,post_date,post_time,day,hour,time_slot,content_category,content_format,reach,likes,comments,shares,engagement,engagement_rate
0,ACC_7336,POST_200000,2024-04-27,System_A,Mobile,YouTube,2024-05-09,21:15,Thursday,21.0,Evening,Entertainment,Shorts,85350.0,10087.0,1130.000,740.0,11957.0,0.140
1,ACC_6851,POST_200001,2024-01-20,System_A,Creator Studio,Instagram,2024-01-21,21:00,Sunday,21.0,Evening,Education,Carousel,116999.0,7415.0,1995.000,1493.0,10903.0,0.093
2,ACC_1381,POST_200002,2023-11-25,System_C,Creator Studio,YouTube,2024-01-12,10:15,Friday,10.0,Morning,Tech,Shorts,44142.0,4258.0,443.000,267.0,4968.0,0.113
3,ACC_2851,POST_200003,2024-02-26,System_B,Creator Studio,Instagram,2024-03-24,18:00,Sunday,18.0,Evening,Entertainment,Carousel,155962.0,13398.0,2167.375,1662.0,16901.0,0.103
4,ACC_3976,POST_200004,2024-10-18,System_A,Web,Instagram,2024-12-13,07:15,Friday,7.0,Morning,Lifestyle,Reel,104647.0,10536.0,1933.000,1183.0,13652.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,ACC_6122,POST_207995,2024-06-01,System_C,Creator Studio,Facebook,2024-07-14,11:15,Sunday,11.0,Morning,Sports,Video,63764.0,5717.0,718.000,543.0,1261.0,0.020
7996,ACC_9163,POST_207996,2024-08-11,System_B,Web,YouTube,2024-09-25,13:30,Wednesday,13.0,Afternoon,Entertainment,Shorts,96142.0,3920.0,1523.000,831.0,6274.0,0.065
7997,ACC_3786,POST_207997,2024-07-30,System_B,Mobile,Facebook,2024-08-28,14:15,Wednesday,14.0,Afternoon,Lifestyle,Text,29221.0,3196.0,508.000,367.0,4071.0,0.139
7998,ACC_2754,POST_207998,2024-08-02,System_A,Creator Studio,Instagram,2024-09-08,22:00,Sunday,22.0,Night,Business,Reel,87859.0,6740.0,622.000,607.0,7362.0,0.084
7999,ACC_6888,POST_207999,2024-03-09,System_B,Mobile,Instagram,2024-04-27,22:30,Saturday,22.0,Night,Entertainment,Image,155962.0,13470.5,2167.375,1450.0,16901.0,0.141

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account_id        8000 non-null   object
 1   post_id           8000 non-null   object
 2   id_created_date   8000 non-null   object
 3   data_source       8000 non-null   object
 4   posting_device    8000 non-null   object
 5   platform          8000 non-null   object
 6   post_date         8000 non-null   datetime64[ns]
 7   post_time         8000 non-null   object
 8   day               8000 non-null   object
 9   hour              8000 non-null   float64
 10  time_slot         8000 non-null   object
 11  content_category  8000 non-null   object
 12  content_format    8000 non-null   object
 13  reach             8000 non-null   float64
 14  likes             8000 non-null   float64
 15  comments          8000 non-null   float64
 16  shares            8000 non-null   float64
 17  engagement        8000 non-null   float64
 18  engagement_rate   8000 non-null   float64
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 1.2+ MB

In [29]:
df.isna().sum()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account_id        8000 non-null   object
 1   post_id           8000 non-null   object
 2   id_created_date   8000 non-null   object
 3   data_source       8000 non-null   object
 4   posting_device    8000 non-null   object
 5   platform          8000 non-null   object
 6   post_date         8000 non-null   datetime64[ns]
 7   post_time         8000 non-null   object
 8   day               8000 non-null   object
 9   hour              8000 non-null   float64
 10  time_slot         8000 non-null   object
 11  content_category  8000 non-null   object
 12  content_format    8000 non-null   object
 13  reach             8000 non-null   float64
 14  likes             8000 non-null   float64
 15  comments          8000 non-null   float64
 16  shares            8000 non-null   float64
 17  engagement        8000 non-null   float64
 18  engagement_rate   8000 non-null   float64
dtypes: datetime64[ns](1), float64(7), object(11)
memory usage: 1.2+ MB

,post_date,hour,reach,likes,comments,shares,engagement,engagement_rate
count,8000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,2024-07-04 07:21:00,15.601125,79582.335125,6274.441813,933.782938,671.536875,7527.289125,0.094874
min,2024-01-01 00:00:00,6.000000,25478.000000,1162.000000,118.000000,62.000000,139.000000,0.014500
25%,2024-04-04 00:00:00,11.000000,57608.250000,4141.750000,566.750000,372.000000,4889.750000,0.076000
50%,2024-07-05 12:00:00,16.000000,75051.000000,5717.000000,838.000000,607.000000,6945.000000,0.097000
75%,2024-10-04 00:00:00,20.000000,96949.750000,7873.250000,1207.000000,888.000000,9694.250000,0.117000
max,2024-12-31 00:00:00,23.000000,155962.000000,13470.500000,2167.375000,1662.000000,16901.000000,0.153000
std,NaN,5.120869,29463.241420,2865.054897,488.600524,382.474754,3694.436179,0.029061

In [28]:
#Exporting the file
df.to_csv("Social Media Analytics 2024 8K.csv", index=False)